#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NowPlayingLib.SonyDatabase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class MtDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    #endregion
		
		public MtDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MtDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MtDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MtDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ObjectTable> ObjectTable
		{
			get
			{
				return this.GetTable<ObjectTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="t_object")]
	public partial class ObjectTable
	{
		
		private int _Id;
		
		private System.Nullable<int> _SpecId;
		
		private string _Name;
		
		private System.Nullable<int> _BitRate;
		
		private System.Nullable<int> _TrackNumber;
		
		private System.Nullable<int> _SamplingRate;
		
		private string _Genre;
		
		private string _Artist;
		
		private string _ArtworkPath;
		
		private string _Album;
		
		private string _Kind;
		
		private string _Composer;
		
		private System.Nullable<System.DateTime> _DateAdded;
		
		private System.Nullable<System.DateTime> _ReleaseDate;
		
		private System.Nullable<System.DateTime> _PlayedDate;
		
		private System.Nullable<double> _Duration;
		
		private string _FilePath;
		
		public ObjectTable()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ObjectId", Storage="_Id")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ObjectSpecId", Storage="_SpecId")]
		public System.Nullable<int> SpecId
		{
			get
			{
				return this._SpecId;
			}
			set
			{
				if ((this._SpecId != value))
				{
					this._SpecId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ObjectName", Storage="_Name")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="104", Storage="_BitRate")]
		public System.Nullable<int> BitRate
		{
			get
			{
				return this._BitRate;
			}
			set
			{
				if ((this._BitRate != value))
				{
					this._BitRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="106", Storage="_TrackNumber")]
		public System.Nullable<int> TrackNumber
		{
			get
			{
				return this._TrackNumber;
			}
			set
			{
				if ((this._TrackNumber != value))
				{
					this._TrackNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="116", Storage="_SamplingRate")]
		public System.Nullable<int> SamplingRate
		{
			get
			{
				return this._SamplingRate;
			}
			set
			{
				if ((this._SamplingRate != value))
				{
					this._SamplingRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="200", Storage="_Genre")]
		public string Genre
		{
			get
			{
				return this._Genre;
			}
			set
			{
				if ((this._Genre != value))
				{
					this._Genre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="201", Storage="_Artist")]
		public string Artist
		{
			get
			{
				return this._Artist;
			}
			set
			{
				if ((this._Artist != value))
				{
					this._Artist = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="202", Storage="_ArtworkPath")]
		public string ArtworkPath
		{
			get
			{
				return this._ArtworkPath;
			}
			set
			{
				if ((this._ArtworkPath != value))
				{
					this._ArtworkPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="206", Storage="_Album")]
		public string Album
		{
			get
			{
				return this._Album;
			}
			set
			{
				if ((this._Album != value))
				{
					this._Album = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="208", Storage="_Kind")]
		public string Kind
		{
			get
			{
				return this._Kind;
			}
			set
			{
				if ((this._Kind != value))
				{
					this._Kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="216", Storage="_Composer")]
		public string Composer
		{
			get
			{
				return this._Composer;
			}
			set
			{
				if ((this._Composer != value))
				{
					this._Composer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="300", Storage="_DateAdded")]
		public System.Nullable<System.DateTime> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this._DateAdded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="301", Storage="_ReleaseDate")]
		public System.Nullable<System.DateTime> ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}
			set
			{
				if ((this._ReleaseDate != value))
				{
					this._ReleaseDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="303", Storage="_PlayedDate")]
		public System.Nullable<System.DateTime> PlayedDate
		{
			get
			{
				return this._PlayedDate;
			}
			set
			{
				if ((this._PlayedDate != value))
				{
					this._PlayedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="400", Storage="_Duration")]
		public System.Nullable<double> Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this._Duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="500", Storage="_FilePath")]
		public string FilePath
		{
			get
			{
				return this._FilePath;
			}
			set
			{
				if ((this._FilePath != value))
				{
					this._FilePath = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
